# Matrica 

In [12]:
import numpy as np
import Matrica as mat

# Dekompozicija

## LU Dekompozicija

In [13]:
class LU_dekompozitor:
    
    def __init__(self):
        self.jedinicna_matrica = None
    
    def dekompozicija(self, matrica):
        for i in range(self.brRed-1):
            for j in range(i+1, self.brRed):
                if matrica.elementi[i, i] == 0: 
                    print("Pivot je 0.")
                    return
                matrica.elementi[j][i] = matrica.elementi[j][i] / matrica.elementi[i][i]
                
                for k in range (i+1, matrica.brStup):
                    matrica.elementi[j][k] -= matrica.elementi[j][i] * matrica[i][k]
        
        self.identity_matrix = Matrica(matrica.brRed, matrica.brStup, True)

## LUP Dekompozicija

In [14]:
class LUP_Dekompozitor:
    
    def __init__(self):
        self.permutacijska_matrica = None
        self.brPermutacija = 0
        
    def dekompozicija(self, matrica):
        p = np.array(range(matrica.brRed))
        self.permutationCount = matrica.brRed

        for i in range(matrica.brRed):
            pivot = i 
            for j in (i+1, matrica.brRed):
                if(abs(matrica.elementi[j][i]) > abs(matrica[pivot][i])):
                    pivot = j

            if pivot != i:
    #             input_seq[ix1], input_seq[ix2] = input_seq[ix2], input_seq[ix1]
                p[i], p[pivot] = p[pivot], p[i]
            

## Testiranje

In [15]:
arr = np.array(range(7))
print(arr[4])

4


In [16]:
el7 = [[6., 2., 10.], [2., 3., 0.], [0., 4., 2.]]
mat7 = mat.Matrica(3, 3, False, el7)
b7 = mat.Matrica(3, 3, False, [2., 3., 4.])

In [18]:
el4 = [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]
el5 = [[9., 8., 7.], [6., 5., 4.], [3., 2., 1.]]
mat4 = mat.Matrica(3, 3, False, el4)
mat5 = mat.Matrica(3, 3, False, el5)

In [19]:
el6 = [[3, 9, 6], [4, 12, 12], [1, -1, 1]]
b = [12, 12, 1]
vektor_b = mat.Matrica(1, 3, False, b) 
mat6 = mat.Matrica(3, 3, False, el6)

In [20]:
vektor_y = mat6.supst_unaprijed(vektor_b)
print(mat6.supst_unazad(vektor_y))

[-34  44 -47]


In [21]:
print(vektor_b)
print(vektor_b.elementi.T)

z = vektor_b.elementi.copy()
z[1] = 999
print(z)
print(vektor_b)

[12 12  1]
[12 12  1]
[ 12 999   1]
[12 12  1]


In [22]:
mat1 = mat.Matrica(3, 3, True)
mat2 = mat.Matrica(3, 3, True)

In [23]:
mat3 = mat1*mat2
print(mat3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
mat6 = mat4*mat5
print(mat6)

[[ 30.  24.  18.]
 [ 84.  69.  54.]
 [138. 114.  90.]]


In [25]:
mat3 = mat1 + mat2 
mat3.elementi[0][1] = 7
print(mat3.dohvatiStupac(1))

[7.0, 2.0, 0.0]


In [26]:
print(mat3.transpose())

[[2. 0. 0.]
 [7. 2. 0.]
 [0. 0. 2.]]


In [27]:
mat1.elementi[0][1] = 8
print(mat1.elementi)
print(mat1.elementi.T)

[[1. 8. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [8. 1. 0.]
 [0. 0. 1.]]


In [28]:
mat7 = mat1*3
print(mat7)

[[ 3. 24.  0.]
 [ 0.  3.  0.]
 [ 0.  0.  3.]]


In [29]:
for i in range(mat1.brRed):
    z = list(zip(mat1.elementi[i], mat2.elementi[i]))
#     print(z)
    m = list(map(sum, z))
    print(m)

print(mat1 == mat2)

[2.0, 8.0, 0.0]
[0.0, 2.0, 0.0]
[0.0, 0.0, 2.0]
False


In [30]:
print(mat1*3)
print(mat1)

[[ 3. 24.  0.]
 [ 0.  3.  0.]
 [ 0.  0.  3.]]
[[1. 8. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
mat1 -= mat2
print(mat1)

[[0. 8. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
even_numbers = [2,3]
even_numbers_squared = [4, 8]
zipped_result = zip(even_numbers, even_numbers_squared)

In [33]:
z = list(zipped_result)
print(z)

[(2, 4), (3, 8)]


In [34]:
print(z)

[(2, 4), (3, 8)]


In [35]:
type(z)

list

In [36]:
if type(z) == list: print("True")

True


In [39]:
l = list(range(1, 11))

In [ ]:
l[]