# Matrica 

In [1]:
import numpy as np
from Matrica import Matrica

## 1. zadatak  
#### Kakva treba biti usporedba double varijabli kako bi uspoređivanje dalo očekivane rezultate? Isprobajte operator == s elementima matrice kao necijelim brojevima, pomnožite i podijelite sa realnim brojem i usporedite s originalom. 

In [2]:
matrica = Matrica.citaj_iz("a1.txt")
print(matrica)

m11 = matrica * 7.847390456847390456
print(m11)
m12 = m11 * (1. / 7.847390456847390456)
print(m12)

print(matrica == m12)

[[1.2   2.34  3.453]
 [4.23  5.56  6.97 ]
 [7.3   8.245 9.789]]
[[ 9.41686855 18.36289367 27.09703925]
 [33.19446163 43.63149094 54.69631148]
 [57.28595033 64.70173432 76.81810518]]
[[1.2   2.34  3.453]
 [4.23  5.56  6.97 ]
 [7.3   8.245 9.789]]
True


## 2. zadatak
#### Riješite sustav zadan matricama u nastavku. Odredite može li se riješiti LU odnosno LUP dekompozicijom

In [3]:
m21 = Matrica.citaj_iz("a21.txt")
v21 = Matrica.citaj_iz("a22.txt")
rjesenje = m21.rijesi_jednadzbu(v21, False)
if rjesenje is not None: print(rjesenje)

m22 = Matrica.citaj_iz("a21.txt")
v22 = Matrica.citaj_iz("a22.txt")

rjesenje = m22.rijesi_jednadzbu(v22, True)
if rjesenje is not None: print(rjesenje)



Dekompozicija matrice nije bila moguca: Pivot je nula.
[[ 3.]
 [ 1.]
 [-1.]]


## 3. zadatak
#### Zadanu matricu rastavite na LU odnosno LUP. Ako je ovom matricom predstavljen sustav jednadžbi, može li se sustav riješiti? (sami definirajte slobodni vektor) 

In [4]:
m31 = Matrica.citaj_iz("a31.txt")
m32 = Matrica.citaj_iz("a31.txt")
m33 = Matrica.citaj_iz("a31.txt")

print(m31.det())

m32.lu_dekompozicija()
m33.lup_dekompozicija()

print(m32)
print(m33)

0.0602
[[ 1.  2.  3.]
 [ 4. -3. -6.]
 [ 7.  2.  0.]]
[[7.   8.   9.  ]
 [0.14 0.86 1.71]
 [0.57 0.5  0.01]]


## 4. zadatak
#### Zadani sustav riješite LU te LUP dekompozicijom. Objasnite razliku u rješenjima! (očituje se prilikom uporabe double varijabli) 

In [19]:
m41 = Matrica.citaj_iz("a41.txt")
m42 = Matrica.citaj_iz("a41.txt")

v41 = Matrica.citaj_iz("a42.txt")
v42 = Matrica.citaj_iz("a42.txt")

print(m41.rijesi_jednadzbu(v41, False, False))
print(m42.rijesi_jednadzbu(v42, True, False))

[[1.00024045]
 [1.99931764]
 [3.00102354]]
[[1.]
 [2.]
 [3.]]


## 5.zadatak
#### Zadani sustav riješite odgovarajućom metodom. Objasnite razliku između dobivenog i točnog rješenja. 

In [20]:
m51 = Matrica.citaj_iz("a51.txt")
v51 = Matrica.citaj_iz("a52.txt")
y = m51.rijesi_jednadzbu(v51, True, False)
print(y)
print(m51*y)
print(v51)


[[ 1.66611055e-03]
 [-7.77444111e-04]
 [ 2.99888889e+00]]
[[3.        ]
 [6.99111629]
 [8.09723323]]
[[6.]
 [9.]
 [3.]]


## 6. zadatak
#### Zadani sustav riješite odgovarajućom metodom. Objasnite razliku između dobivenog i točnog rješenja.

In [21]:
m61 = Matrica.citaj_iz("a61.txt")
v61 = Matrica.citaj_iz("a62.txt")
y = m61.rijesi_jednadzbu(v61, True, False)
print(y)
print(m61*y)
print(v61)

[[ nan]
 [ inf]
 [-inf]]
[[nan]
 [nan]
 [nan]]
[[9.0e+09]
 [1.5e+01]
 [1.5e-09]]


/Users/dunjaacimovic/Code/APR-Python/FirstLab/Matrica.py:201: RuntimeWarning: divide by zero encountered in true_divide
  x[i] = x[i] / self.elementi[i][i]
/Users/dunjaacimovic/Code/APR-Python/FirstLab/Matrica.py:204: RuntimeWarning: invalid value encountered in double_scalars
  x[j][0] -= self.elementi[j][i] * x[i][0]
/Users/dunjaacimovic/Code/APR-Python/FirstLab/Matrica.py:56: RuntimeWarning: invalid value encountered in double_scalars
  m = [pair[0]*pair[1] for pair in z]


## 7. zadatak
#### Korištenjem LUP dekompozicije izračunajte inverz zadane matrice te ispišite dobiveni rezultat: 

## 8.zadatak
#### Korištenjem LUP dekompozicije izračunajte inverz zadane matrice te ispišite dobiveni rezultat: 