In [1]:
from Matrica import Matrica
import numpy as np

In [2]:
broj1 = Matrica(1, 1, [[6]])
broj2 = Matrica(1, 1, [[2]])

vektor1 = Matrica(1, 3, [[1, 2, 3]])
vektor2 = Matrica(1, 3, [[4, 5, 6]])
vektor3 = Matrica(3, 1, [[1], [2], [3]])
vektor4 = Matrica(3, 1, [[4], [5], [6]])

matrica1 = Matrica(3, 3, [[1, 2, 3], [1, 1, 1], [1, 2, 3]])
matrica2 = Matrica(3, 3, [[4, 5, 6], [7, 8, 9], [7, 8, 9]])

In [3]:
print(broj1, broj2)
print(vektor1, vektor2)
print(vektor3)
print(vektor4)
print(matrica1)
print(matrica2)

[[6.]] [[2.]]
[[1. 2. 3.]] [[4. 5. 6.]]
[[1.]
 [2.]
 [3.]]
[[4.]
 [5.]
 [6.]]
[[1. 2. 3.]
 [1. 1. 1.]
 [1. 2. 3.]]
[[4. 5. 6.]
 [7. 8. 9.]
 [7. 8. 9.]]


In [4]:
# Elementi matrice trebaju biti u 2D matrici.
try: 
    Matrica(3, 1, 6)
except Exception as e:
    print(e)

Elementi matrice trebaju biti u 2D matrici.


#### Zbrajanje

In [5]:
print(broj1 + broj2)
print(vektor1 + vektor2)
print(vektor3 + vektor4)
print(matrica1 + matrica2)

[[8.]]
[[5. 7. 9.]]
[[5.]
 [7.]
 [9.]]
[[ 5.  7.  9.]
 [ 8.  9. 10.]
 [ 8. 10. 12.]]


In [6]:
# Pogrešne dimenzije matrica.
try: 
    broj1 + vektor2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (1, 1), a desna (1, 3).


In [7]:
# Pogrešne dimenzije matrica.
try: 
    vektor3 + broj2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (3, 1), a desna (1, 1).


In [8]:
# Pogrešne dimenzije matrica.
try: 
    vektor1 + vektor3
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (1, 3), a desna (3, 1).


In [9]:
# Pogrešne dimenzije matrica.
try: 
    matrica1 + broj2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (3, 3), a desna (1, 1).


In [10]:
# Pogrešne dimenzije matrica.
try: 
    matrica1 + vektor2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (3, 3), a desna (1, 3).


#### Oduzimanje

In [11]:
print(broj1 - broj2)
print(vektor1 - vektor2)
print(vektor3 - vektor4)
print(matrica1 - matrica2)

[[4.]]
[[-3. -3. -3.]]
[[-3.]
 [-3.]
 [-3.]]
[[-3. -3. -3.]
 [-6. -7. -8.]
 [-6. -6. -6.]]


In [12]:
# Pogrešne dimenzije matrica.
try: 
    broj1 - vektor2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (1, 1), a desna (1, 3).


In [13]:
# Pogrešne dimenzije matrica.
try: 
    vektor3 - broj2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (3, 1), a desna (1, 1).


In [14]:
# Pogrešne dimenzije matrica.
try: 
    vektor1 - vektor3
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (1, 3), a desna (3, 1).


In [15]:
# Pogrešne dimenzije matrica.
try: 
    matrica1 + broj2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (3, 3), a desna (1, 1).


In [16]:
# Pogrešne dimenzije matrica.
try: 
    matrica1 - vektor2
except Exception as e:
    print(e)

Pogrešne dimenzije matrica. Lijeva je dimenzija (3, 3), a desna (1, 3).


#### Množenje

In [17]:
# Provjera mnozenja matrica

v1 = Matrica(1, 3, [[1, 2, 3]])
v2 = Matrica(3, 1, [[1], [2], [3]])
m1 = Matrica(3, 3, [[1, 2, 3], [1, 1, 1], [1, 2, 3]])

print("m1/3")
print(m1/3)

print("1/3 * (m1)")
print(1/3 * m1)

# print(m1*v1)
print("m1*v2")
print(m1*v2)
print("v1*m1")
print(v1*m1)
print("m1*m1")
print(m1*m1)
print("v1*v2")
print(v1*v2)
print("v2*v1")
print(v2*v1)

m1/3
[[0.33333333 0.66666667 1.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.66666667 1.        ]]
1/3 * (m1)
[[0.33333333 0.66666667 1.        ]
 [0.33333333 0.33333333 0.33333333]
 [0.33333333 0.66666667 1.        ]]
m1*v2
[[14.]
 [ 6.]
 [14.]]
v1*m1
[[ 6. 10. 14.]]
m1*m1
[[ 6. 10. 14.]
 [ 3.  5.  7.]
 [ 6. 10. 14.]]
v1*v2
[[14.]]
v2*v1
[[1. 2. 3.]
 [2. 4. 6.]
 [3. 6. 9.]]


In [18]:
print(m1.br_stup, v2.br_red, len(m1.elementi[0]), len(v2.elementi))

3 3 3 3
