# Postupci nelinearne optimizacije

In [1]:
import math
import numpy as np
import sys
sys.path.append('../')
from FirstLab.Matrica import Matrica, JedinicnaMatrica

In [20]:
hello = ([1, 2, 3])
matrica = Matrica(3, 3, hello)
matrica1 = Matrica(3, 3, hello)

# print(matrica) 
# print("------------------------")
# print(matrica1)
# print("\n\n")

# matrica[1][1] = 99
matrica1[0] = 99
ms = [matrica, matrica1]
for m in ms: print(m)
print("------------------------")
del ms[0]
for m in ms: print(m)
    
# print(matrica) 
# print("------------------------")
# print(matrica1)
# print("\n\n")
# tuple_example = (1, 1)
# print(matrica[tuple_example])

# matrica[1:3] = [[2, 3, 4], [1, 2, 3]]

# print(matrica)
# stupac = matrica.dohvati_stupac(1)
# print(stupac)
# print(np.mean(matrica.elementi, axis=0))


# matrica.izbrisi_redak(1)
# print(matrica, matrica.br_red)

[1 2 3]
[99  2  3]
------------------------
[99  2  3]


## Zlatni rez

### Traženje unimodalnog intervala

- <b>Ulazne veličine</b>:
    - <b>tocka</b>: početna točka pretraživanja
    - <b>h</b>: pomak pretraživanja
    - <b>f</b>: ciljna funkcija


- <b>Izlazne vrijednosti</b>:
    - <b>unimodalni interval [l, r]</b>

In [4]:
def unimodalni(h, tocka, f):
    
    left = tocka - h 
    right = tocka + h
    m = tocka
    step = 1
    
    fm = f(tocka)
    fl = f(left)
    fr = f(right)
    
    if fm < fr and fm < fl: return
    elif fm > fr:
        while True:
            left = m
            m = right
            fm = fr
            step *= 2
            right = tocka + (h * step)
            fr = f(right)
            if (fm <= fr): break
    else: 
        while True:
            right = m
            m = left
            fm = fl
            step *= 2
            left = tocka - (h * step)
            fl = f(left)
            if(fm <= fl): break
    return left, right

### Postupak zlatnog reza 

- <b>Ulazne veličine</b>:
    - <b>a, b</b>: početne granice unimodalnog intervala
    - <b>epsilon</b>: preciznost

In [12]:
def zlatni_rez(a, b, epsilon):
    c = b - k * (b - a)
    d = a + k * (b - a)
    fc = f(c)
    fd = f(d)
    
    while((b - a) > epsilon):
        if(fc < fd):
            b = d 
            d = c
            c = b - k * (b - a)
            fd = fc
            fc = f(c)
        else:
            a = c
            c = d
            d = a + k * (b - a)
            fc = fd
            fd = f(d)
    return a, b

## Pretraživanje po koordinatnim osima 

In [3]:
# definirati

## Simpleks postupak po Nelderu i Meadu

- <b>Ulazne veličine</b>:
    - <b>x0</b>: početna točka
    - <b>f</b>: funkcija cilja
    - <b>alfa</b>
    - <b>beta</b>
    - <b>gama</b>
    - <b>epsilon</b>


In [20]:
def simplex(x0, alfa = 1.0, beta = 0.5, gama = 2.0, epsilon, f):
    
    #tocke simplexa
    
    pomak = 1
    X = [Matrica(len(x0), 1, x0)]
    for i in len(x0):
        nova_tocka = Matrica(len(x0), 1, x0)
        nova_tocka[i] += pomak
        X.append(nova_tocka)
    
    # - h, l, centroid -
    while True:
        h = index_min(X, f)
        l = index_max(X, f)
        xc = centroid(X, h, f)
        xr = refleksija(xc, X[h], alfa)
        
        if f(xr) < f(x[l]):
            xe = ekspanzija(xc, X[h], gama)
            
            if f(xe) < f(X[h]):
                X[h] = xe
            else:
                X[h] = xr

        else:
            if f(xr) < f(X[h]):
                X[h] = xr
                
            xk = kontrakcija()
            
            if f(xk) < f(X[h]):
                X[h] = xk
            else:
                pomak_prema_xl(X)
        
# - MINIMUM I MAKSIMUM FJE CILJA        
def index_min(X, f):
    i_min = 0
    for i in range(len(X)):
        if f(X[i]) < f(X[i_min]): i_min = i
    return i_min
 
def index_max(X, f):
    i_min = 0
    for i in range(len(X)):
        if f(X[i]) > f(X[i_min]): i_min = i
    return i_min

# - CENTROID -
def centroid(X, h, f):
    tocke = X.copy()
    del tocke[h]
#     return np.mean(tocke, axis=0)

# - REFLEKSIJA, EKSPANZIJA, KONTRAKCIJA -
def refleksija(xc, xh, alfa = 1.0):
    return ((1.0 + alfa) * xc) - (alfa * xh)

def ekspanzija(xc, xr, gama = 2.0):
    return ((1.0 - gama) * xc) + (gama * xr)

def kontrakcija(xh, xc, beta = 0.5):
    return ((1.0 - beta) * xc) + (beta * xh)

def pomak_prema_xl(X):
    for i in range(X.br_red):
        X[i] = 0.5 * (X[i] + )

## Optimizator

In [1]:
class Optimizator:
    
    def __init__(self, pocetna_tocka, minimum):
        self.pocetna_tocka = pocetna_tocka
        self.minimum = minimum
        self.number_of_evaluations = 0

## Funkcije cilja

In [2]:
def f1(x):
    return 100 * (x[1] - (x[0])^2)^2 + (1 - x[0])^2

def f2(x):
    return (x[0] - 4)^2 + 4 * (x[1] - 2)^2

def f3(x):
    result = 0
    for i in len(x):
        result += (x[i] - i)^2
    return result

def f4(x):
    return abs((x[0] - x[1]) * (x[0] + x[1])) + math.sqrt(x[0]^2 + x[1]^2)

def f6(x):
    suma = 0
    for i in range(len(x)):
        suma += x[i]^2
    sinus = math.sin(math.sqrt(suma))
    razlomak = ((sinus^2) - 0.5) / ((1 + 0.001 * suma)^2)
    return 0.5 + razlomak